input {
  http {
    port => 8080
    codec => "json_lines"
  }
}

filter {
  if [status] == "drop_me" {
    drop {}
  }

  mutate {
    add_field => { "processed_by_logstash" => true }
  }
}

output {
  http {
    url => "http://host.docker.internal:5001/"
    http_method => "post"
    format => "json"
    keepalive => true
    automatic_retries => "1"
  }
}

