input {
  http {
    port => 8080
    codec => "json_lines"
  }
}

filter {
  # This is our test condition. If a document has this field, it will be dropped.
  if [status] == "drop_me" {
    drop {}
  }

  # Add a field to all non-dropped events to prove they went through Logstash.
  mutate {
    add_field => { "processed_by_logstash" => true }
  }
}

output {
  # Send each processed event back to our Python listener
  http {
    url => "http://host.docker.internal:5001"
    http_method => "post"
    format => "json"
  }
}
