input {
  http {
    port => 8080
    codec => "json_lines"
  }
}

# FILTER_PLACEHOLDER

output {
  http {
    url => "http://es-run-listener:8081/"
    http_method => "post"
    format => "json_batch"
    keepalive => false
  }
}