input {
  http {
    port => 8080
    codec => "json_lines"
  }
}

filter {
    # Controleer of het een OOTS-log is met potentiele XML-content.
    if [logger] == "OOTS" and [log][nonRepudiationInformation] {

        # Gebruik een tijdelijk metadata-veld om de XML-string in op te slaan.
        mutate {
            add_field => { "[@metadata][xml_content]" => "" }
        }

        # Haal de XML-string op, ongeacht de locatie.
        if [log][nonRepudiationInformation][content] {
            mutate {
                copy => { "[log][nonRepudiationInformation][content]" => "[@metadata][xml_content]" }
                remove_field => ["[log][nonRepudiationInformation][content]"]
            }
        } else if [log][nonRepudiationInformation][firstPart][content] {
            mutate {
                copy => { "[log][nonRepudiationInformation][firstPart][content]" => "[@metadata][xml_content]" }
                remove_field => ["[log][nonRepudiationInformation][firstPart][content]"]
            }
        }

        # Parse de XML als er content is gevonden.
        if [@metadata][xml_content] and [@metadata][xml_content] != "" {
            xml {
                source      => "[@metadata][xml_content]"
                target      => "[log][parsedXml]"
                force_array => false
            }

            # Hernoem het geparste object op basis van de XML root-tag (Request of Response)
            if [log][parsedXml][Query] {
                mutate { rename => { "[log][parsedXml]" => "[log][parsedQueryRequest]" } }
            } else if [log][parsedXml][RegistryObjectList] or [log][parsedXml][Exception] {
                mutate { rename => { "[log][parsedXml]" => "[log][parsedQueryResponse]" } }
            } else {
                mutate { add_tag => ["_oots_xml_type_unknown"] }
            }
        }
    }
}

output {
  #stdout { codec => rubydebug }
  http {
    url => "http://es-run-listener:8081/"
    http_method => "post"
    format => "json_batch"
    keepalive => false
  }
}

